# Generated by Django 4.1 on 2022-12-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('post_slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
                ('post_content', models.TextField(max_length=450000, verbose_name='Содержание')),
                ('post_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('post_time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('post_media', models.ImageField(blank=True, default='default.png', upload_to='%Y/%m/%d/', verbose_name='Медиа')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sitelogic.postcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['post_title', 'post_content'],
            },
        ),
    ]
