# Generated by Django 4.1 on 2022-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hit',
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
