# Generated by Django 4.1 on 2023-01-12 12:55

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0003_post_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckeditor_test', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
    ]
