# Generated by Django 4.1 on 2023-01-13 11:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0004_skeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
