# Generated by Django 4.1 on 2023-01-13 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0005_alter_post_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SKEditor',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(max_length=450000, verbose_name='Содержание'),
        ),
    ]
