# Generated by Django 4.1 on 2023-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0008_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(max_length=450000, verbose_name='Содержание'),
        ),
    ]
