# Generated by Django 4.1 on 2023-02-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0015_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_media',
            field=models.ImageField(default='default.png', upload_to='%Y/%m/%d/', verbose_name='Превью'),
        ),
    ]
