# Generated by Django 4.1 on 2023-02-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0017_alter_post_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_media',
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sitelogic.postcategory', verbose_name='Форум'),
        ),
    ]
