# Generated by Django 4.1 on 2023-04-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0020_post_viewed_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
