# Generated by Django 4.1 on 2023-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0022_ip_remove_post_viewed_ip_delete_userip_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.AddField(
            model_name='post',
            name='viewed_ip',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='sitelogic.userip'),
        ),
    ]
