# Generated by Django 4.1 on 2023-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0023_userip_remove_post_views_delete_ip_post_viewed_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vvv',
            field=models.CharField(blank=True, max_length=50, verbose_name='Просмотревшие IP'),
        ),
    ]
