# Generated by Django 4.1 on 2023-04-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0024_post_vvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitelogic.post'),
        ),
    ]
