# Generated by Django 4.1 on 2023-04-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0026_comment_post_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='sitelogic.post'),
        ),
    ]
