# Generated by Django 4.1 on 2023-04-14 09:40

from django.db import migrations, models
import django.db.models.deletion
import sitelogic.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0027_remove_post_post_comment_comment_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(blank=True, default=sitelogic.models.Post, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='sitelogic.post'),
        ),
    ]
