# Generated by Django 4.1 on 2023-05-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0033_remove_comment_parent_comment_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_com', to='sitelogic.comment'),
        ),
    ]
