# Generated by Django 4.1 on 2023-05-08 10:23

from django.db import migrations, models
import django.db.models.deletion
import sitelogic.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelogic', '0034_alter_commentreply_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=sitelogic.models.CommentReply.get_parent_comment, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_com', to='sitelogic.comment'),
        ),
    ]
